# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform ClickHouse installation tasks
  block:
    - name: Validate ClickHouse configuration
      when: clickhouse_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install ClickHouse
      when: clickhouse_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-clickhouse
    - install-all
    - install-clickhouse

- name: Perform ClickHouse uninstallation tasks
  block:
    - name: Uninstall ClickHouse
      when: not clickhouse_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-clickhouse
