# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure ClickHouse service is started
  ansible.builtin.service:
    name: "{{ clickhouse_identifier }}"
    state: started
    daemon_reload: true
  register: clickhouse_ensure_started_result

- name: Wait a bit, so that ClickHouse can start
  when: clickhouse_ensure_started_result.changed | bool
  ansible.builtin.wait_for:
    timeout: "{{ clickhouse_managed_databases_service_start_wait_timeout_seconds }}"
  delegate_to: 127.0.0.1
  become: false

- name: Prepare managed ClickHouse database
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/util/prepare_managed_database.yml"
  with_items: "{{ clickhouse_managed_databases }}"
  loop_control:
    loop_var: managed_db
  # Suppress logging to avoid dumping the credentials to the shell
  no_log: true

- name: Ensure ClickHouse systemd service is stopped (if it previously was)
  when: clickhouse_ensure_started_result.changed | bool
  ansible.builtin.service:
    name: "{{ clickhouse_identifier }}"
    state: stopped
